### PR TITLE
feat: Use ResizeObserver to listen to size changes

### PR DESCRIPTION
**Pull request by christiankaindl**
Reduces idle CPU usage and should also improve scrolling performance. The previous approach used a `requestAnimationFrame()` loop with calls to `getBoundingClientRect()` on every frame.

Fixes https://github.com/TanStack/virtual/issues/359

Before
Screen Shot 2022-08-02 at 20 29 51

After (+ dark mode 😄):
Screen Shot 2022-08-03 at 00 54 43

Verified it still works, the number of items increase and decrease when resizing:

https://user-images.githubusercontent.com/15364860/182487611-ec7a2635-e86f-4961-89a5-67908b9641e5.mov

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Fantastic! Would you mind making this same change in react-charts? ;)

**Comment by tannerlinsley** [comment]
The release is failing because of the dependency removal. It changed the output structure of the rollup files. npm run build locally and ensure the exports in package.json map to the correct output files.

**Comment by wuarmin** [comment]
@tannerlinsley  would it be possible to release a new beta.15?
Thanks!

**Comment by christiankaindl** [comment]
Thanks for merging so fast, awesome! 🙌

> Would you mind making this same change in react-charts? ;)

Sure, I will give it a try, probably later today.

> The release is failing because of the dependency removal. It changed the output structure of the rollup files. npm run build locally and ensure the exports in package.json map to the correct output files.

Should I push to this branch or create a new PR?

**Pull request merged**
