### PR TITLE
fix(react-virtual): add missing react-dom peer dependencies

### LINKED ISSUE #612: Getting `Can't resolve 'react-dom'` since v3.0.0-beta.66 with yarnpnp
### Describe the bug

```
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/builds/.yarn/__virtual__/next-virtual-8c8169bd6a/4/build-cache/yarn/cache/next-npm-13.5.6-306005c39c-10c0.zip/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[7].oneOf[11].use[1]!/builds/.yarn/__virtual__/next-virtual-8c8169bd6a/4/build-cache/yarn/cache/next-npm-13.5.6-306005c39c-10c0.zip/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[7].oneOf[11].use[2]!/builds/.yarn/__virtual__/graphiql-virtual-d77f03f872/4/build-cache/yarn/cache/graphiql-npm-3.0.6-b00ac37a08-10c0.zip/node_modules/graphiql/graphiql.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 2 items } -> webpack/lib/ModuleWarning -> Warning
Failed to compile.
../.yarn/__virtual__/@tanstack-react-virtual-virtual-b320c29aa3/4/build-cache/yarn/cache/@tanstack-react-virtual-npm-3.0.0-beta.66-a58275e017-10c0.zip/node_modules/@tanstack/react-virtual/build/lib/index.mjs:13:0
Module not found: Can't resolve 'react-dom'
```

### Your minimal, reproducible example

https://github.com/simPod/repro-virutal

```sh
cd client
yarn install
yarn run build
```

### Steps to reproduce

- use yarn pnp
- add `@tanstack/react-virtual to ^3.0.0-beta.66`

### Expected behavior

No error

### How often does this bug happen?

always

### Platform

any

### tanstack-virtual version

3.0.0-beta.66

### TypeScript version

5.2.2

### Additional context

3.0.0-beta.65 is ok

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### PR DESCRIPTION
**Pull request by piecyk**
closes #612

### CODE REVIEW

**Comment by simPod** [comment]
thanks. can we publish the release to npm?

**Comment by piecyk** [comment]
> thanks. can we publish the release to npm?

Yes, it’s already there.

**Comment by simPod** [comment]
Can you recheck?

image

https://www.npmjs.com/package/@tanstack/react-virtual

**Comment by piecyk** [comment]
Ooo looks like something went wrong while auto publishing 😞

**Comment by piecyk** [comment]
@simPod checkout the [3.0.0-beta.68](https://www.npmjs.com/package/@tanstack/react-virtual/v/3.0.0-beta.68)

**Comment by simPod** [comment]
CI is green now thanks!

**Pull request merged**
