### PR TITLE
refactor: memoize notify

### PR DESCRIPTION
**Pull request by piecyk**

### CODE REVIEW

**Review by andreial — APPROVED** [review]
👍

**Comment by guysympoly** [comment]
Hi @piecyk, please note that removing `measureElement` and the generic signature `<TItemElement extends Element>`  from `VirtualItem` is a breaking change. It just bit me really hard during a pipeline.

**Comment by piecyk** [comment]
> Hi @piecyk, please note that removing `measureElement` and the generic signature `<TItemElement extends Element>` from `VirtualItem` is a breaking change. It just bit me really hard during a pipeline.

Yes, sorry for that, got mixed up with auto publish script we have.

**Comment by juzerzarif** [comment]
Will there be a release on the v3 line to fix the breaking change? Also just ran into this

**Comment by piecyk** [comment]
> Will there be a release on the v3 line to fix the breaking change? Also just ran into this

Yeah sorry for that, not planing any more on 3x. 

In the end adding generic to VirtualItem was a breaking change at first.

**Pull request merged**
